version: '3.8'

services:
  1090merge:
    build:
      context: .
      # Use current directory instead of hardcoded path
      dockerfile: Dockerfile
    environment:
      - HOSTS="192.168.1.100,192.168.1.101,192.168.1.102"
      # do not use quotes if single host only
    init: true
    # init: true is required for proper signal handling in Alpine Linux
    # This ensures graceful shutdown and proper cleanup of background processes
    volumes:
      - ./data:/data
      - ./backup:/backup
